### ISSUE TITLE
Flycheck appears to report success when verification times out

### ISSUE THREAD

**Issue by 0xabu** [boogie-org/boogie-friends#13]
I have a nasty lemma that times out without reporting any specific failures; command-line Dafny gives:

```
Verifying Impl$$_module.__default.lemma__ARM__L1PTE__Validity ...
  [62.239 s, 67 proof obligations]  timed out
pagedb.i.dfy(227,6): Verification of 'Impl$$_module.__default.lemma__ARM__L1PTE__Validity' timed out after 60 seconds
```

However, when I open this file in Emacs, I don't see any red squigglies, and the status bar shows only "(Dafny ... FlyC)" as if there were no errors.

**Comment by cpitclaudel** [comment]
Can you try running the Dafny checker with checker `C-c ! C-c` in Emacs? Does it print the same thing there?

Also, which verification method are you using? The server-based one, or the plain one?

**Comment by 0xabu** [comment]
I was using the server, and `C-c ! C-c` doesn't seem to work with it. If I switch to the cli backend, then I see the same timeout message as the last line above printed in the Flycheck output buffer, along with the tooltips. I still don't reliably see red squigglies in the display.

I say reliably, because _sometimes_ Dafny produces information on where it timed out (e.g. an assertion or a calc line), and if it does that then I see it as a squiggly-line failure and as an additional error message in `C-c ! C-c`, but this information is unstable, and, in my experience, not usually helpful.

**Comment by cpitclaudel** [comment]
Got it, thanks :) I'll look into it.

**Comment by cpitclaudel** [comment]
Thanks for the report! Should be fixed now.  New version should be up on MELPA in a few hours.  Testing appreciated!

**Comment by 0xabu** [comment]
Seems to be working. Thanks!

**Comment by cpitclaudel** [comment]
Great, thanks for testing!
