### ISSUE TITLE
Flycheck ignores Boogie errors if they lack proper location information

### ISSUE THREAD

**Issue by wilcoxjay** [boogie-org/boogie-friends#18]
Sometimes, Boogie will report errors without providing location information. (This could be due to the error having no true source-level location, for example.) In that case, the flycheck error patterns simply fail to match the error, which can lead to believing a file verifies, when in fact it does not.

**Comment by wilcoxjay** [comment]
I took a crack at this [here](https://github.com/wilcoxjay/boogie-friends/commit/d6128daafe3f768167edd7787f5276a0184cb505) by making the filename optional. 

In my specific use case, the actual fix was to hack boogie to output more useful error information, but making the error pattern more liberal is still worthwhile because otherwise it can be very difficult to realize that boogie is actually reporting errors to you!

**Comment by cpitclaudel** [comment]
Ah, so when you say it lacks location information you mean just the file name?

**Comment by cpitclaudel** [comment]
If so, then this commit looks good. Can you make a PR?

**Comment by wilcoxjay** [comment]
Good question. It lacks all location information, but when the "empty" location gets printed, it prints as `(0,0)` (ie, as a location with no filename, line number 0, and column number 0). Thus the only change to the pattern necessary is for the filename.

I'll make a PR.
