### ISSUE TITLE
Move temporary file for current buffer outside current folder

### ISSUE THREAD

**Issue by LukeXuan** [boogie-org/boogie-friends#22]
When the buffer is opened the temporary file for flycheck to verify is annoying, especially when you want to do stuff with git. Would it be better to move them to more convenient temporary file provided by `mktemp` or so?

**Comment by cpitclaudel** [comment]
We already do it when we can.  Which checker do you have in mind?

**Comment by cpitclaudel** [comment]
I don't think it can be done with the current Dafny and Boogie, due to includes. But the inferior-dafny checker doesn't require temporary files, and it has better performance. Can you try that?

**Comment by LukeXuan** [comment]
Hi, I currently using `DafnyServer` through setting `flycheck-inferior-dafny-executable` and `dafny-verification-backend` to `'server`. Is this what you mean? If so, I'm still observing `flycheck_xxxxx.dfy` file generating in my folder.

**Comment by cpitclaudel** [comment]
Ah, right, I remember now.

**Comment by cpitclaudel** [comment]
Can you try adding `(setq-default inferior-dafny--in-memory t)` to your `.emacs`?

**Comment by LukeXuan** [comment]
wow that's it. I think it's working perfectly now. Both the temporary file disappeared and flycheck is still working correctly.

**Comment by cpitclaudel** [comment]
Super. Can you also try this slightly trickier but likely better fix? Change the definition of inferior-dafny-get-source-as-string from this:

```
(defun inferior-dafny-get-source-as-file ()
  "Save a snapshot of the buffer and return its path in a plist."
  (let ((temp-fname (flycheck-save-buffer-to-temp
                     #'flycheck-temp-file-inplace)))
    `(:source ,temp-fname :sourceIsFile t)))
```

to that:

```
(defun inferior-dafny-get-source-as-file ()
  "Save a snapshot of the buffer and return its path in a plist."
  (let ((temp-fname (flycheck-save-buffer-to-temp
                     #'flycheck-temp-file-system)))
    `(:source ,temp-fname :sourceIsFile t)))
```

**Comment by LukeXuan** [comment]
After my testing with `(setq-default inferior-dafny--in-memory t)` commented out. In server mode the flycheck file does not appear either and works well(with simple includes), and in CLI mode it still appears(I think it should be). Hope these result would be helpful.

**Comment by cpitclaudel** [comment]
Neat, thanks.  Let's do the following: can you keep this patch applied for a week or so (and maybe @wilcoxjay can apply it too).  If no new problems pop up, I'll push the fix. Thanks for bringing this to my attention!

**Comment by LukeXuan** [comment]
I'm glad to, but my current focus is still on coq. I will report one or two weeks later.

**Comment by wilcoxjay** [comment]
@cpitclaudel This has been working well for me so far. I'd move to merge it.
