### ISSUE TITLE
Strange indentation/whitespace in Boogie mode

### ISSUE THREAD

**Issue by bkragl** [boogie-org/boogie-friends#27]
**Symptom**

In the following, `↓` denotes the cursor position and `▯` denotes a space.

*Example 1:* If I have
```
procedure foo () {↓
```
then typing `}` results in
```
procedure foo () {}↓▯
```

*Example 2:* If I have
```
procedure foo () {
↓
```
then typing `}` results in
```
procedure foo () {
}↓▯▯▯▯▯▯▯▯▯
```

**Cause**

In contrast to Dafny mode (which has `dafny-indent-keep-position`), Boogie mode does not set a custom `indent-line-function`. I don't know to which function it actually points to in Boogie mode, but it causes the above behavior in `boogie-friends-self-insert-and-indent`.

**Possible Solutions**

1. Move the keybinding for `}` from `boogie-friends.el` into `dafny-mode.el`.
2. Use (a potentially adapted) `dafny-indent`/`dafny-indent-keep-position` in Boogie mode. I can't say I understand the code, but in a quick experiment just using these functions in Boogie mode seemed to behave reasonable.

Any advice?

**Comment by cpitclaudel** [comment]
Blast! Thanks for the report.

> Move the keybinding for } from boogie-friends.el into dafny-mode.el.

This is probably the best course of action.  Can you make a patch?

> Use (a potentially adapted) dafny-indent/dafny-indent-keep-position in Boogie mode. 

That would be great.  The code is finicky but not super complicated.  The alternative would be to implement an SMIE parser for Dafny/Boogie: http://www.iro.umontreal.ca/~monnier/smie.pdf (cc @monnier), or (more agressively) recreate Dafny-/Boogie-mode on top of CC-mode.  I also think @monnier has a simpler mode for C-like languages that we could build on top, maybe?

**Comment by bkragl** [comment]
> > Move the keybinding for } from boogie-friends.el into dafny-mode.el.
> 
> This is probably the best course of action. Can you make a patch?

For my purposes this is currently good enough.
