### ISSUE TITLE
No syntax errors when using Dafny server

### ISSUE THREAD

**Issue by ningit** [boogie-org/boogie-friends#4]
Only verification errors are reported when using the Dafny server backend. Syntax, type checking and symbol resolution errors aren't shown. When the default backend is used instead, all errors are reported.

~~Could that be related to the fact that Dafny server returns `[SUCCESS]` when these errors occur?~~ I'm using Dafny 1.9.7.

And thanks for this useful mode!

**Comment by cpitclaudel** [comment]
Hi,

Thanks for the bug report! Do you have a small example of problematic code? I'm having trouble repducing the issue (for example, I'm not seeing this with the following code; I do get an error on the `:=`)

```
method A(x: int) returns (y: int) {
  y := true;
}
```

**Comment by ningit** [comment]
Hi,

I'm not getting an error on the `:=` with your example. 

I can only see the error when `(setq dafny-verification-backend 'server)` is commented in `init.el`: 

```
(require 'package)
(add-to-list 'package-archives
    '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(setq dafny-verification-backend 'server)
(setq flycheck-dafny-executable "dafny")
(setq flycheck-inferior-dafny-executable "dafny-server")
```

However it seems that `dafny-server` works because when I add `(setq inferior-dafny--debug t)` the following appears in the _Messages_ buffer:

```
[inferior-dafny-filter-live] [/tmp/example.dfy(2,3): Error: RHS (of type bool) not assignable to LHS (of type int)
^[[37mVerification completed successfully!
[SUCCESS] [[DAFNY-SERVER: EOM]]
```

**Comment by cpitclaudel** [comment]
Hey there,

Which platform are you using this on? GNU/Linux, or Windows? If Windows, which Emacs are you using? Cygwin?

That `^[[37m` in the message looks suspicious.

Clément.

**Comment by ningit** [comment]
Yes, `^[[37m` is suspicious. I should have guessed. It's an [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code) to reset the foreground color back to white after setting it to red to print the error message. The problem seems to be that `dafny-server` is producing colored output, and the terminal control codes appear in what Emacs reads.

I'm using GNU/Linux Ubuntu and Emacs 24.5 with GTK (from the official repository).

I have carried out some experiments:
1. If I run `dafny-server` manually at the command line (with the base64 message and all that), the output is colored as if I were using the command line interface.
2. Mono checks whether the output channel is interactive (~[`isatty`](http://man7.org/linux/man-pages/man3/isatty.3.html)) and doesn't write control codes for colors when it is not. In _cli_ mode it's likely the case.
3. In _server_ mode, when called, `dafny-server`'s standard output is interactive (`isatty` returns _true_).
4. When using _server_ mode and <kbd>C-c C-c</kbd> `dafny` is called with _custom_ environment variables. One of them is `TERM=dumb`. When `dafny-server` is called automatically, there is `TERM=xterm-256color` instead, the default.

**Conclusion:** invoking Emacs with `TERM=dumb emacs example.dfy` solves the problem rudimentaryly. But what I have written in 1 or 3 are unwanted facts, aren't they?

**Comment by cpitclaudel** [comment]
Sorry for the delay. I can reproduce this when I start Emacs in command line mode with term set to `xterm-256color`. The details are [here](https://stackoverflow.com/questions/12979140/mono-console-app-in-256-color-terminal). I think number 1 is generally fine; if you pipe into `cat`, for example, you'll get no colors. 3 is an issue, which I'll fix ASAP :)

**Comment by cpitclaudel** [comment]
Should be fixed :) Thanks for the report. The issue was that Emacs was using a TTY to talk to dafny-server, instead of a pipe.

**Comment by ningit** [comment]
Thanks :). I have tried the fixed mode and it works fine.

**Comment by cpitclaudel** [comment]
Wonderful, thanks so much for the report!
