### ISSUE TITLE
Consider documenting the value of /printTooltips

### ISSUE THREAD

**Issue by 0xabu** [boogie-org/boogie-friends#7]
Thanks for dafny-mode and friends. By accident, I discovered that if I add:

```
(setq dafny-prover-custom-args '("/printTooltips"))
```

... to my `.emacs`, then I get handy tooltips for selected triggers and decreases clauses. Perhaps consider documenting this feature in the README?

**Comment by cpitclaudel** [comment]
That's right, thanks for reporting. It should be switched on by default.

Back when that setting I added that setting to Dafny it was only available in trunk, but now it should be common enough to make it the default. (double-checking: @RustanLeino, do you confirm?)

I'm impressed by the investigation skills. Did you find about it from `Dafny /h`?
